name:                jpl-hs
version:             0.1.0.0
github:              "luochen1990/jpl-hs"
license:             Apache-2.0
author:              "LuoChen"
maintainer:          "luochen1990@gmail.com"
copyright:           "2020 LuoChen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/luochen1990/jpl-hs#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- transformers
- mtl
- hspec
- QuickCheck
- bytes
- cereal
- bytestring
- megaparsec
- parser-combinators
- raw-strings-qq
- pretty-simple
- text

library:
  source-dirs: src

executables:
  jpl-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jpl-hs

tests:
  jpl-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jpl-hs
